### ISSUE TITLE
Stoke introducing def in register

### ISSUE THREAD

**Issue by rknath** [eschkufz/stoke-release#9] opened 2015-01-28 03:22 UTC
In one case, I found stoke proposing instruction that reads a register which is not in def in set. 

are you aware of such cases ?

The code is something like below. ( I can't share the full code here .. will try to get a short code)

movdqa 0x1000, %xmm1 
movdqa %xmm1, %xmm2 
movdqa %xmm1, %xmm3 
........
........
........

becomes ...

movaps x1000, %xmm1 
pxor %xmm1, %xmm2 
movdqa %xmm1, %xmm3 
...........
.........
..........

Given that %xmm2 was not in defined in register set and was initialized with 0x00..00 in all the testcases, it seems to be doing correct thing during search.

**Comment by stefanheule** [comment] 2015-01-28 03:25
STOKE will not propose any program that reads registers which aren't defined (i.e., written to by some earlier instruction, or in def-in).  If you see different behavior, then that is likely a bug.  Can you give us a full example (all code, configuration files and command line commands you used) so we can reproduce this?  Otherwise there is nothing we can do.

**Comment by rknath** [comment] 2015-01-28 05:45
I will try to write a small example and reproduce the case. 

I am curious to know if STOKE check the defined in register constraint for all the generated code that passes the training /test cases. Does it ? 

In some instance there might be nothing wrong with introducing a seemingly defined in register. 
For example, there may be an instruction ... 
movq $0, %rax  with %rax not marked as defined in ..
stoke may replace it with 
xor %rax, %rax ... 

So keeping a check might be useful. But putting a constraint may not be desirable.

**Comment by stefanheule** [comment] 2015-01-28 06:04
STOKE uses a dataflow analysis to determine if a piece of code reads an undefined value, and there are certainly cases where the analysis is not precise enough to realize that a piece of code is not reading an undefined value.  The examples you gave, however, are both correctly recognized as not reading any registers.

We have not experimented with turning this check off.

**Comment by rknath** [comment] 2015-01-28 19:49
Is the data flow analysis is done for each intermediate code ? 

I guess one of the missing cases could be ... pcmpeqX instructions

**Comment by bchurchill** [comment] 2015-01-28 20:58
The dataflow analysis is done for every single instruction.  The semantics are given by the x64asm project; it has a spreadsheet documenting the read/write/undef set of registers for each.  

However, because we look at the read/write set for each opcode, independent of the operands, 

*If you find any example where stoke proposes a rewrite that reads an undefined register, that's a bug, and you should send us all the details -- meaning a config file and all your assembly sources.*  You can post it on another site or email if github doesn't work for sharing.

**Comment by rknath** [comment] 2015-01-28 21:38
Thanks a lot. 
  I will definitely email.

**Comment by bchurchill** [comment] 2015-02-03 05:06
Is there anything here the stoke developers should follow-up on?  If not, I would like to close this issue.

**Comment by rknath** [comment] 2015-02-03 05:38
sorry .. I couldn't reproduce with a smaller example. You can probably close it now. I will share once I reproduce the issue.

**Comment by bchurchill** [comment] 2015-02-03 06:05
Thank you.

**Closed by bchurchill** 2015-02-03 06:05 UTC
